import "@/app/app.css";
import NavBar from "../components/navBar.jsx";
import { Roboto } from "next/font/google";

export const metadata = {
  title: "App en Fase de Desarollo",
  description: "Generated by create next app",
};

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  style: ["italic", "normal"],
  subsets: ["latin"],
});


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <NavBar title={"Barra de Navegacion "} />

        {children}
      </body>
    </html>
  );
}
